# Symbolic links to create.
# Relatives target paths are relative to $HOME. Relative source paths are relative to the root of
# this repo. Absolute paths are not modified.
---
- target_path: .gitconfig
  source_path: dotfiles/gitconfig

- target_path: .npmrc
  source_path: dotfiles/npmrc

- target_path: Library/Application Support/Code/User/settings.json
  source_path: vscode_settings.json


- target_path: /usr/local/bin/git-cleanup
  source_path: git-cleanup
