# Symbolic links to create.
# Relative target paths are relative to $HOME. Relative source paths are relative to the root of
# this repo. Absolute paths are not modified.
---
- target_path: .zshenv
  source_path: config/dotfiles/zshenv

- target_path: .zshrc
  source_path: config/dotfiles/zshrc

- target_path: .gitconfig
  source_path: config/dotfiles/gitconfig

- target_path: .npmrc
  source_path: config/dotfiles/npmrc

- target_path: Library/Application Support/Code/User/settings.json
  source_path: config/vscode_settings.json


- target_path: /usr/local/bin/git-cleanup
  source_path: bin/git-cleanup
